development:
  adapter: postgresql
  database: chansey_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: chansey_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: chansey_production
  pool: 5
  timeout: 5000